module.exports = {
    printWidth: 160,
    tabWidth: 4,
    useTabs: false,
    semi: true,
    singleQuote: true,
    quoteProps: 'preserve',
    jsxSingleQuote: false,
    trailingComma: 'es5',
    bracketSpacing: true,
    arrowParens: 'avoid',
    rangeStart: 0,
    rangeEnd: Infinity,
    requireConfig: false,
    requirePragma: false,
    insertPragma: false,
    endOfLine: 'auto',
    HTMLWhitespaceSensitivity: 'css',
    proseWrap: 'preserve',
    eslintIntegration: false,
    tslintIntegration: false,
    stylelintIntegration: false,
    ignorePath: '.prettierignore',
    disableLanguages: [''],
};